name         'stdmod-elasticsearch'
version      '0.0.1'
author       'Stdmod authors'
license      'Apache2'
project_page 'https://github.com/stdmod'
source       'https://github.com/stdmod/puppet-elasticsearch'
summary      'Puppet module for elasticsearch'
description  'This module installs and manages elasticsearch. Check README for details.'
dependency   'puppetlabs/stdlib', '>=2.0.0'
